tools:
    external_code_coverage:
        timeout: 60
build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=turbo-coverage --report-useless-tests --strict-coverage --bootstrap ./tests/bootstrap.php ./tests
                coverage:
                    file: turbo-coverage
                    format: php-clover
