build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=zepi-turbo-coverage'
                coverage:
                    file: 'zepi-turbo-coverage'
                    format: 'clover'

filter:
    excluded_paths:
        - tests/*
