build:
    environment:
        php: '7.0'
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=zepi-turbo-coverage.clover'
                coverage:
                    file: 'zepi-turbo-coverage.clover'
                    format: 'clover'

filter:
    excluded_paths:
        - tests/*
