language: php

php:
  - 5.6

before_install:
  - pip install --user codecov

after_success:
  - codecov

before_script: 
  - travis_retry composer self-update 
  - travis_retry composer install --no-interaction --prefer-source --dev 

script: 
  - vendor/bin/phpunit --coverage-clover=coverage.xml 

