<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'zepi\\turbo\\backend\\filebackend' => '/../src/Zepi/Turbo/Backend/FileBackend.php',
                'zepi\\turbo\\backend\\fileobjectbackend' => '/../src/Zepi/Turbo/Backend/FileObjectBackend.php',
                'zepi\\turbo\\backend\\objectbackendabstract' => '/../src/Zepi/Turbo/Backend/ObjectBackendAbstract.php',
                'zepi\\turbo\\exception' => '/../src/Zepi/Turbo/Exception.php',
                'zepi\\turbo\\framework' => '/../src/Zepi/Turbo/Framework.php',
                'zepi\\turbo\\frameworkinterface\\clieventhandlerinterface' => '/../src/Zepi/Turbo/FrameworkInterface/CliEventHandlerInterface.php',
                'zepi\\turbo\\frameworkinterface\\datasourceinterface' => '/../src/Zepi/Turbo/FrameworkInterface/DataSourceInterface.php',
                'zepi\\turbo\\frameworkinterface\\eventhandlerinterface' => '/../src/Zepi/Turbo/FrameworkInterface/EventHandlerInterface.php',
                'zepi\\turbo\\frameworkinterface\\filterhandlerinterface' => '/../src/Zepi/Turbo/FrameworkInterface/FilterHandlerInterface.php',
                'zepi\\turbo\\frameworkinterface\\sessioninterface' => '/../src/Zepi/Turbo/FrameworkInterface/SessionInterface.php',
                'zepi\\turbo\\frameworkinterface\\webeventhandlerinterface' => '/../src/Zepi/Turbo/FrameworkInterface/WebEventHandlerInterface.php',
                'zepi\\turbo\\manager\\datasourcemanager' => '/../src/Zepi/Turbo/Manager/DataSourceManager.php',
                'zepi\\turbo\\manager\\modulemanager' => '/../src/Zepi/Turbo/Manager/ModuleManager.php',
                'zepi\\turbo\\manager\\requestmanager' => '/../src/Zepi/Turbo/Manager/RequestManager.php',
                'zepi\\turbo\\manager\\routemanager' => '/../src/Zepi/Turbo/Manager/RouteManager.php',
                'zepi\\turbo\\manager\\runtimemanager' => '/../src/Zepi/Turbo/Manager/RuntimeManager.php',
                'zepi\\turbo\\module\\moduleabstract' => '/../src/Zepi/Turbo/Module/ModuleAbstract.php',
                'zepi\\turbo\\request\\clirequest' => '/../src/Zepi/Turbo/Request/CliRequest.php',
                'zepi\\turbo\\request\\requestabstract' => '/../src/Zepi/Turbo/Request/RequestAbstract.php',
                'zepi\\turbo\\request\\webrequest' => '/../src/Zepi/Turbo/Request/WebRequest.php',
                'zepi\\turbo\\response\\response' => '/../src/Zepi/Turbo/Response/Response.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
